// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpwBfUAJjEpmICTwEOFnGkaCOwaIP76s',
    appId: '1:83665095683:android:5875e6732c88092e6a9236',
    messagingSenderId: '83665095683',
    projectId: 'active-324c2',
    storageBucket: 'active-324c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurA9XpKs0tpEQWNgGgH4Lorky-R6C3zw',
    appId: '1:83665095683:ios:b1f1c720341856cb6a9236',
    messagingSenderId: '83665095683',
    projectId: 'active-324c2',
    storageBucket: 'active-324c2.firebasestorage.app',
    iosBundleId: 'com.example.parkitClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWBUuIx9wVRv-P0GqURuqdbIi1byORqbE',
    appId: '1:83665095683:web:59cf448417b8f9566a9236',
    messagingSenderId: '83665095683',
    projectId: 'active-324c2',
    authDomain: 'active-324c2.firebaseapp.com',
    storageBucket: 'active-324c2.firebasestorage.app',
  );
}
